var sweety="sweety";
var cutie="cutie";
console.log("......Before swap........");
console.log("sweety:",sweety);
console.log("cutie:",cutie);
var temp=sweety;
sweety=cutie;
cutie=temp;
console.log("..........After swap.......");
console.log("sweety:",sweety);
console.log("cutie:",cutie);
console.log("--------------------");
var num1=100;
var num2=200;
var num3=300;
console.log("......Before swap........");
console.log("num1:",num1);
console.log("num2:",num2);
console.log("num3:",num3);
console.log("......After  swap........");
var num1=num3-num1;
var num2=num1+num3-num2;
var num3=num2-num1;
console.log("num1:",num1);
console.log("num2:",num2);
console.log("num3:",num3);
